---
version: '3'

includes:
    simple:
        taskfile: ./example/simple/TaskFile.yml
        dir: ./example/simple

tasks:
    clean:
        cmds:
            - rm -rf .terraform
            - rm terraform.tfstate || true
            - rm terraform.tfstate.backup || true
            - rm .terraform.lock.hcl || true

    init:
        deps: [clean]
        cmds:
            - terraform init -backend=false {{ .CLI_ARGS }}

    check:
        deps: [init]
        cmds:
            - terraform validate {{ .CLI_ARGS }}
            - tflint --init
            - tflint --recursive
            - terraform-docs .
            - terraform fmt

    docs:
        cmds:
            - terraform-docs .